### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by Andrey-Shypko** [trufanov-nok/minidjvu-mod-gui#1]
Пишет:
"This application failed to start because it could not find or load the Qt platform plugin "windows"
 in "" .
Reinstalling the application may fix this problem.
Windows 7 64
Win64-minidjvu-mod-gui_0.2.2

**Comment by trufanov-nok** [comment]
Ок... доложу эту dll'ку.

**Comment by trufanov-nok** [comment]
Теперь должно быть исправлено в GUI 0.2.2 (обновил) и в свежем 0.2.3. Доложена библиотека "platforms/windows.dll"
