### ISSUE TITLE
Не открывается out.djvu

### ISSUE THREAD

**Issue by Andrey-Shypko** [trufanov-nok/minidjvu-mod-gui#2]
minidjvu-mod.exe "1.tif" out.djvu
Просмотрщик STDUViewer.ru не может открыть out.djvu, другие просмотрщики открывают нормально. Возможно причина в отсутствии в начале файла записи "AT&TFORM"

**Comment by trufanov-nok** [comment]
Спасибо. Да, я недавно обнаружил эту проблему. Она присутствует для всех докумументов, состоящих только из 1-й страницы. Проблема исправлена в master ветке minidjvu-mod, но проекты еще не пересобраны, т.к. есть еще одна проблема, которую я хотел бы исправить перед релизом. Со дня на день надеюсь это сделать.

**Comment by trufanov-nok** [comment]
Должно быть исправлено в свежем minidjvu-mod 0.9m05, который идет вместе с minidjvu-mod GUI v. 0.2.3
Добавил сборку под Windows: https://github.com/trufanov-nok/minidjvu-mod-gui/releases/tag/0.2.3
