### ISSUE TITLE
Неработает с многостраничным tif

### ISSUE THREAD

**Issue by Andrey-Shypko** [trufanov-nok/minidjvu-mod-gui#3]
Обрабатывает только первую страницу.

**Comment by trufanov-nok** [comment]
Хм, должно работать. Можно мне на почту прислать этот многостраничный tif?

**Comment by trufanov-nok** [comment]
Да, подтвердил проблему. Она только под Windows. Буду чинить.

**Comment by trufanov-nok** [comment]
Проблема была в том, что libminidjvu-mod-settings.dll был собран без поддержки libtiff под Windows. Пересобрал, обновил в minidjvu-mod 0.9m03 и minidjvu-mod GUI 0.2.2. Ну и в свежих версиях, естественно.
Рекомендую попробовать minidjvu-mod GUI 0.2.3 с minidjvu-mod 0.9m05 на борту. 
https://github.com/trufanov-nok/minidjvu-mod-gui/releases/tag/0.2.3
Там новый классификатор, который жрет меньше памяти и должен быть более надежен с т.з. ошибок классификации (пока недостаточно протестирован).

Что касается цветных изображений, упомянутых в письме - minidjvu-mod с ними не работает. В Djvu черно/белый текст и иллюстрации кодируются принципиально по-разному. minidjvu-mod кодирует только текстовую часть и не имеет автоматического сегментатора, чтобы отделять зоны текста от иллюстраций. В качестве полуавтоматического сегментатора сканов может применяться ScanTailor Universal, а для сборки отдельно закодированного текста и иллюстраций - программа DjVu Imager (умеет уставлять картинки в любой ч./б. многостроничный DjVu документ). И тогда получится создание книги по "методу раздельных сканов". Предполагается что в  ScanTailor Universal 0.3.х minidjvu-mod вообще будет встроен штатно и будет добавлен этап создания книги из сканов.

Коммерческий documenttodjvu.exe имеет встроенный сегментатор, но он, видимо, достаточно примитивен, т.к. наиболее темные участки иллюстраций могут опознаваться как текст, и кодироваться как текст, что несколько портит иллюстрации.
